
exports.up = function(knex) {
  return knex.raw(
    `
        CREATE TABLE "doctors"(
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            name text NOT NULL,
            specialization text NOT NULL
        );

        CREATE TABLE "hospitals"(
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            name text NOT NULL,
            location text NOT NULL
        );

        CREATE TABLE "hospital_doctors"(
            doctor_id integer NOT NULL,
            hospital_id integer NOT NULL,
            FOREIGN KEY (doctor_id) REFERENCES "doctors"(id),
            FOREIGN KEY (hospital_id) REFERENCES "hospitals"(id)
        );
    `
  );
};

exports.down = function(knex) {
  return knex.raw(
    `
        DROP TABLE hospital_doctors;
        DROP TABLE hospitals;
        DROP TABLE doctors;
    `
  );
};
